import { test, expect } from '@playwright/test';

test.describe('Profile Management', () => {
  test.beforeEach(async ({ page }) => {
    // Login first
    await page.goto('/login');
    await page.fill('input[name="email"]', 'studentdemo123@sliit.lk');
    await page.fill('input[name="password"]', 'Demo123@');
    await page.click('button[type="submit"]');
    await expect(page).toHaveURL(/.*dashboard/);
    
    // Navigate to Profile
    await page.goto('/profile');
  });

  test('should edit profile details successfully', async ({ page }) => {
    // Click on Edit Info tab
    await page.click('button:has-text("Edit Info")');

    // Fill some details
    await page.fill('input[name="headline"]', 'Future Software Engineer | Playwright Enthusiast');
    await page.fill('textarea[name="bio"]', 'This is a test bio generated by automated Playwright tests to verify the profile update functionality.');
    
    // Changing location
    await page.fill('input[name="location.city"]', 'Kandy');
    
    // Click Save
    await page.click('button[type="submit"]');

    // Check for success toast or indicator
    // The EditInfoTab shows "Nexus Synced!" on the button itself or a toast
    await expect(page.locator('text=Profile saved successfully')).toBeVisible();

    await page.screenshot({ path: 'test-results/screenshots/profile-edit-success.png', fullPage: true });
  });
});
